title: Data Vis Activities for Children
logo: /assets/img/logo.png
description: "Data Vis Activities for Children: Hands-on Exploration of Activities & Challenges around Visual, Physical and Tangible Representations for Play and Data Literacy"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
repository: visualinteractivedata/idc-workshop-2026
